"""
Combines Signal A (LLM) and Signal B (Stylometric) into a final classification.

Formula (from spec):
    base = 0.6 × LLM_confidence + 0.4 × stylometric_confidence
    agree  → final_confidence = base
    disagree → final_confidence = base × 0.77

Thresholds:
    ≥ 0.85        → high confidence  (AI or Human)
    0.60 – 0.84   → moderate confidence (AI or Human)
    < 0.60        → uncertain
"""

_LABELS = {
    ("AI",    "high"):     ("high_confidence_ai",   "Likely AI-Generated",
                            "Our system found strong indicators that this content was generated using AI tools."),
    ("Human", "high"):     ("high_confidence_human", "Likely Human-Written",
                            "Our system found strong indicators that this content was written by a human author."),
    ("AI",    "moderate"): ("possible_ai",           "Possibly AI-Generated",
                            "Our analysis leans toward this content being AI-generated, but the signal is not strong enough to be certain."),
    ("Human", "moderate"): ("possible_human",        "Possibly Human-Written",
                            "Our analysis leans toward this content being human-written, but the signal is not strong enough to be certain."),
    ("uncertain", "low"):  ("uncertain",             "Attribution Uncertain",
                            "Our system could not confidently determine whether this content was written by a human or generated by AI."),
}


def _label(classification: str, confidence: float) -> dict:
    if confidence >= 0.85:
        tier = "high"
    elif confidence >= 0.60:
        tier = "moderate"
    else:
        classification = "uncertain"
        tier = "low"

    key, title, message = _LABELS[(classification, tier)]
    return {"key": key, "title": title, "message": message}


def evaluate(llm_result: dict, stylometric_result: dict) -> dict:
    """
    Returns:
        {
            "classification": "AI" | "Human" | "uncertain",
            "confidence":     float,
            "label":          {"key": str, "title": str, "message": str},
        }
    """
    llm_pred = llm_result["prediction"]
    llm_conf = llm_result["confidence"]
    sty_pred = stylometric_result["prediction"]
    sty_conf = stylometric_result["confidence"]

    base = 0.6 * llm_conf + 0.4 * sty_conf
    agree = llm_pred == sty_pred
    final_confidence = round(base if agree else base * 0.77, 3)

    # LLM carries 60% weight, so it drives the prediction direction on disagreement.
    prediction = llm_pred

    attribution = "uncertain" if final_confidence < 0.60 else prediction

    return {
        "attribution": attribution,
        "confidence": final_confidence,
        "label": _label(attribution, final_confidence),
    }
