import json
import re

import config
from groq import Groq

_client = Groq(api_key=config.GROQ_API_KEY)

_SYSTEM_PROMPT = """You are an AI content detector. Analyze the text and determine whether it was written by a human or generated by AI.

Respond ONLY with a JSON object in this exact format, with no extra text:
{"prediction": "AI" or "Human", "confidence": <float 0.0–1.0>}

Scoring guidance:
- 0.5 = genuinely unsure
- 0.9+ = very strong signal
- AI writing: uniformly polished, coherent, predictable structure, consistent tone
- Human writing: irregular tone, uneven structure, personal phrasing, idiosyncratic word choices"""


def classify(text: str) -> dict:
    """
    Runs LLM-based classification on text.

    Returns:
        {
            "prediction": "AI" | "Human",
            "confidence": float  # 0.0 – 1.0
        }
    """
    response = _client.chat.completions.create(
        model=config.GROQ_MODEL,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.1,
        max_tokens=64,
    )

    raw = response.choices[0].message.content.strip()

    match = re.search(r"\{.*?\}", raw, re.DOTALL)
    parsed = json.loads(match.group(0) if match else raw)

    prediction = parsed.get("prediction", "")
    if prediction not in ("AI", "Human"):
        prediction = "Human"  # safe fallback; low confidence signals uncertainty downstream

    confidence = float(parsed.get("confidence", 0.5))
    confidence = max(0.0, min(1.0, confidence))

    return {"prediction": prediction, "confidence": confidence}
